### ISSUE TITLE
Listening to long key press

### ISSUE THREAD

**Issue by naonvl** [thiagobrez/capacitor-volume-buttons#1]
Hi there, i'd like to know if this can handle longkeypress event ?

**Comment by thiagobrez** [comment]
Hey @naonvl ! No, longkeypress is not yet supported

**Comment by thiagobrez** [comment]
@naonvl This repo has been merged into https://github.com/capacitor-community/volume-buttons, where it is going to be actively maintained. You should request this feature there!
