### ISSUE TITLE
Background mode?

### ISSUE THREAD

**Issue by diegoromerohuertas** [thiagobrez/capacitor-volume-buttons#2]
Hey man, love your plugin, works very good in foreground mode.

Thing is, I have an Android app working now in background mode, and I can not get your plugin to work when the app is in background.

Any suggestions?

Thanks.

**Comment by thiagobrez** [comment]
Hey @diegoromerohuertas ! Glad you like it. I've reached the same issue on iOS, whenever I changed context, backgrounded or similar, the listener seems to stop. I don't know how to solve this yet, might take a look in a few weeks, but got no clue as of now. If you find anything and want to discuss/open a PR would be awesome. Thanks!

**Comment by poolerMF** [comment]
@thiagobrez 
what about this solution ?
https://www.npmjs.com/package/background-volume-buttons

**Comment by thiagobrez** [comment]
@diegoromerohuertas @poolerMF This repo has been merged into https://github.com/capacitor-community/volume-buttons, where it is going to be actively maintained. You should request this feature there!
