### ISSUE TITLE
Not working, if volume = 100% or volume = 0%

### ISSUE THREAD

**Issue by poolerMF** [thiagobrez/capacitor-volume-buttons#4]
iOS:
If volume = 100% and I press VOLUME UP key
or
IF volume = 0% and I press VOLUME DOWN key 

then, listener volumeButtonPressed is not called - it's bad behaviour
that listener need to tell if volume button is pressed, not if volume is changed
try to call that listener every time and add another info - "volumeChanged: true|false" if volume was changed

**Comment by ryaa** [comment]
I think that this problem should be fixed in this plugin https://github.com/capacitor-community/volume-buttons

**Comment by thiagobrez** [comment]
This repo is no longer actively maintained as I'm not currently working with Capacitor. Please head to https://github.com/capacitor-community/volume-buttons as @ryaa mentioned :)
