### ISSUE TITLE
Licensing: Please add a license to this repository

### ISSUE THREAD

**Issue by ryaa** [thiagobrez/capacitor-volume-buttons#5]
I'm planning to publish https://github.com/capacitor-community/volume-buttons plugin and reference your plugin there as some implementation is inspired by your brilliant work. As [github suggests](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license), an unlicensed repository is protected by the default copyright laws, so I can't use it, just view.

Can you please add a license (Apache License Version 2.0 is preferred - see https://github.com/thiagobrez/capacitor-volume-buttons/pull/6) to this repository otherwise I won't be able to refer to/re-use your code.

thank you

**Comment by thiagobrez** [comment]
Of course @ryaa, happy that it helped! Just merged the license

**Comment by ryaa** [comment]
Awesome. Thank you for the quick turnaround on this! :)
